config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :survey_answers
  resources :answers
  resources :questions
  resources :visitors
  resources :contacts

end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers, :dependent => :destroy, :autosave => true
	has_many :survey_answers 

	accepts_nested_attributes_for :answers, allow_destroy: true, :reject_if => proc { |att| att[:answer].blank? }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    2.times { @question.answers.build }
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :active, :answers_attributes => [:answer, :votes, :vote_ratio])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<% if current_user.admin == true %>

<h1>Go To Admin</h1>

<h2><%= link_to "Click here to go to Admin", '/admin' %></h2>

<%= link_to 'Back To Home', root_path %>

<% else %>

<% if current_user %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
<% end %><br>

<% end %>

app/views/questions/index.html.erb
<% if current_user.admin == true %>

<h1>Go To Admin</h1>

<h2><%= link_to "Click here to go to Admin", '/admin' %></h2>

<%= link_to 'Back To Home', root_path %>

<% else %>

<% if current_user %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
<% end %><br>

<% end %>

app/views/questions/new.html.erb
<div class="container">

	<% if flash[:notice] %>
	    <div class="notice"><h3><%= flash[:notice] %></h3></div>
	<% end %>
	<h1>Create New Question</h1>

	<%= nested_form_for @question do |f| %>
		<br>
		Question: <%= f.text_area :question, class: "form-control" %><br/>
		<div class="field">
		    <%= f.label :active %><br>
		    <%= f.check_box :active, class: "form-control" %>
		</div>
		
		<%= f.fields_for :answers do |builder| %>
			<p>	
				Answer: <%= builder.text_field :answer, class: "form-control" %>
				<%= builder.link_to_remove "Remove this answer" %><br/>
			</p>
		<% end %>
		<p><%= f.link_to_add "Add a answer +", :answers, class: "btn btn-primary btn-xs" %></p><br>


	<%= f.submit "Submit Question", class: "btn btn-danger" %>

	<% end %>
	<br>
	<%= link_to "Back to Question List", questions_path %>
</div>

app/views/questions/show.html.erb
<% if current_user.admin == true %>

<h1>Go To Admin</h1>

<h2><%= link_to "Click here to go to Admin", '/admin' %></h2>

<%= link_to 'Back To Home', root_path %>

<% else %>

<% if current_user %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
<% end %><br>

<% end %>