config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :survey_answers
  resources :answers
  resources :questions
  resources :visitors
  resources :contacts

end

app/views/pages/_contact.html.erb
<section class="contact-section">
	<div class="page-title">
  		CONTACT
	</div>
	<div style="overflow: hidden;">
		 <div class="product-video-container" style="margin-top:0; margin-bottom:20px;">
	      <div class="video-mask contact-video-mask">
	        <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster75.png" id="video75" class="contact-video-footer">
	          <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-75.mp4" type="video/mp4">
	          Your browser does not support HTML5 video.
	        </video>
	        <img id="75" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
	      </div>
	     </div>
    </div>
	<div>
		<div class="main-text" style="margin:10px 0;">
			IN THE NEAR FUTURE, THE POWER OF FAST MESSAGING AND SHORT VIDEO WILL TRULY BE IN YOUR HANDS!
		</div>
		<div class="main-text" style="margin: 10px 0;">info@facepopme.com</div>
	</div>
	<div class="social">
		<div class="fb-like"
			data-href="https://www.facebook.com/facepopapp/"
			data-layout="standard"
			data-action="like"
			data-show-faces="true">
		</div>
		<a href="https://www.facebook.com/facepopapp/" class="social-links" target="_blank"><img src="https://s3-us-west-2.amazonaws.com/facepop/social/icon_facebook.png" width="75" class="social-link-icon"></a>
		<a href="https://twitter.com/FacepopApp" class="social-links" target="_blank"><img src="https://s3-us-west-2.amazonaws.com/facepop/social/icon_twitter.png" class="social-link-icon"></a>
		<a href="https://www.instagram.com/facepopapp/" class="social-links" target="_blank"><img src="https://s3-us-west-2.amazonaws.com/facepop/social/icon_instagram.png" class="social-link-icon"></a>
		<a href="https://www.pinterest.com/facepopcompany/" class="social-links" target="_blank"><img src="https://s3-us-west-2.amazonaws.com/facepop/social/icon_pinterest.png" class="social-link-icon"></a>
		<a href="https://plus.google.com/u/0/112716641914283714321/posts" class="social-links" target="_blank"><img src="https://s3-us-west-2.amazonaws.com/facepop/social/icon_google_plus.png" class="social-link-icon"></a>
	</div>
	<div class="main-text" style="margin: 15px 0;">
		INVESTMENT INQUIRIES ARE WELCOME
	</div>
	<div class="copy-text" style="">
		USPTO/Patent Pending/File Serial No. 15/355,038
	</div>
	<div class="footer-videos" style="overflow: hidden;">
<!-- 		<div class="product-video-container footer-video" style="display: inline-block; margin: auto;">
	      <div class="video-mask contact-video-mask">
	        <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster-glasses.png" id="video16" class="contact-video-footer">
	          <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-16.mp4" type="video/mp4">
	          Your browser does not support HTML5 video.
	        </video>
	        <img id="16" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
	      </div>
	    </div>
		<div class="product-video-container footer-video" style="display: inline-block;">
	      <div class="video-mask contact-video-mask ">
	        <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster-no-glasses.png" id="video36" class="contact-video-footer">
	          <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-36.mp4" type="video/mp4">
	          Your browser does not support HTML5 video.
	        </video>
	        <img id="36" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
	      </div>
	    </div> -->

		<div class="product-video-container footer-video" style="display: inline-block;">
	      <div class="video-mask contact-video-mask ">
	        <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster51.png" id="video51" class="contact-video-footer">
	          <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-51.mp4" type="video/mp4">
	          Your browser does not support HTML5 video.
	        </video>
	        <img id="51" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
	      </div>
	  </div>
	  <div class="product-video-container footer-video" style="display: inline-block;">
      <div class="video-mask contact-video-mask ">
        <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster38.png" id="video38" class="contact-video-footer">
          <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-38.mp4" type="video/mp4">
          Your browser does not support HTML5 video.
        </video>
        <img id="38" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
      </div>
	   </div>
		<div class="product-video-container footer-video" style="display: inline-block;">
	      <div class="video-mask contact-video-mask ">
	        <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster75.png" id="video135" class="contact-video-footer" style="left:-62px;">
	          <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-135.mp4" type="video/mp4">
	          Your browser does not support HTML5 video.
	        </video>
	        <img id="135" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
	      </div>
	   </div>
	</div>
	<div class="copy-text" style="">
		&copy; 2016 The Facepop Company, All Rights Reserved
	</div>
</section>

app/views/pages/_email.html.erb
<section class="email-section" style="padding: 100px 0;">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div style="text-align: center; padding-bottom: 20px; font-size: 25px;">
					Sign Up for Updates
				</div>
				<%= form_for Contact.new, {class: "form-inline"} do |f| %>
						<div class="col-xs-10">
							<%= f.text_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}', :placeholder => "Enter Your Email", class: "form-control input-lg" %>
						</div>
						<div class="col-xs-2">
							<%= f.submit 'Submit', :class => "btn btn-primary btn-lg sub-btn" %>
						</div>

				<% end %>

			</div>

		</div>
		<div style="text-align: center; padding: 50px; font-size: 35px;">
			UNDER CONSTRUCTION
		</div>
	</div>

</section>

app/views/pages/_hero.html.erb
<section class="hero-section">
	<div class="hero-title-container">
		<div class="page-title hero-title">
	    	<!-- FACEPOP<span class="glyphicon glyphicon-registration-mark hero-title__trademark" aria-hidden="true"></span> -->
	  	</div>
	</div>
</section>

app/views/pages/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
          <div class="product-video-container" style="margin-top:0; margin-bottom:20px;">
            <div class="video-mask contact-video-mask">
              <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster25.png" id="video161" class="contact-video-footer" autoplay>
                <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-161.mp4" type="video/mp4">
                Your browser does not support HTML5 video.
              </video>
            </div>
            <img id="161" class="play-button play-button-modal mobile-show product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
        </div>
      <%= form_for(@visitor, remote: true) do |f| %>

        <div class="modal-body">
            <% if @visitor.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

                <ul>
                <% @visitor.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
                <%= f.select :age, options_for_select(["15 or lower", "16 35", "36 or higher"]), {prompt: "Select Age Group"}, {required: true, class: 'form-control input-lg'} %>
            </div>
            <div class="field">
                <%= f.select :gender, options_for_select(["Male", "Female"]), {prompt: "Select Gender"}, {required: true, class: 'form-control input-lg'} %>
            </div>
            <div class="field">
              <%= f.text_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}', :placeholder => "Enter Your Email", class: "form-control input-lg" %>
            </div>
            <div class="field">
              <%= f.number_field :zip, :required => true, :placeholder => "Enter Your Zip", class: "form-control input-lg" %>
            </div>
            <div class="actions">

            </div>

        </div>
        <div class="modal-footer">
          <%= f.submit 'Submit', :class => "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/pages/_nav.html.erb
<nav class="" style="height:80px;">
  <div class="container">
    <a href="#survey-section"><span class="page-scroll"><img src="https://s3-us-west-2.amazonaws.com/facepop/survey-button.png" style="height:97px; width:226px; display: block; margin: auto;" class="blink_me"></span></a>
  </div>
</nav>

<script>
	(function blink() { 
	  $('.blink_me').fadeOut(1000).fadeIn(1000, blink); 
	})();

	$(function() {
    $('a.page-scroll').bind('click', function(event) {
        var $anchor = $(this);
        $('html, body').stop().animate({
            scrollTop: $($anchor.attr('href')).offset().top
        }, 1500, 'easeInOutExpo');
        event.preventDefault();
    });
});
</script>

app/views/pages/_product.html.erb
<section class="product-section">
  <div class="page-title">
    PRODUCT
  </div>
    <div class="product-video-container" style="margin-top:0; margin-bottom:20px;">
      <div class="video-mask">
        <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster25.png" id="video25" class="contact-video-footer" style="top: -80px; left: -86px;">
          <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-25.mp4" type="video/mp4">
          Your browser does not support HTML5 video.
        </video>
        <img id="25" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
      </div>
    </div>
  <div class="product-content">
  	<div class="main-text" style="margin-bottom:15px;">
  		WE ARE AN EMERGING MOBILE APPLICATION MOTIVATED TO RESHAPE YOUR MESSAGING EXPERIENCE WITH A RECOGNIZABLE MOTION VISUAL EFFECT; THE TALKING HEAD.
  	</div>
  	<div class="main-text" style="margin-bottom:15px;">
  		THE PATENT PENDING FACEPOP ALGORITHM WILL ALLOW USERS TO CREATE AND SHARE SELF-MADE TALKING HEAD VIDEOS VIA TEXT MESSAGING AND/OR SOCIAL MEDIA PLATFORMS.
  	</div>

    <div class="main-text" style="margin:15px 0;">
    	YOUR SNAPPY FACEPOP MESSAGE MAY INCLUDE:
    </div>

    <div class="row">

      <div class="col-xs-4">
        <div class="product-list-group">
          <ul class="product-list">
            <li>
              Greetings
            </li>
            <li>
              Dramatic and Comical Expressions
            </li>
            <li>
              Well Wishes
            </li>
          </ul>
        </div>

        <div class="product-question">
          <p class="product-questions">ARE THEY GIFs?</p><p>&nbsp;</p>
        </div>
        <div class="product-video-group">
          <div class="product-video-group__item">

            <div class="product-video-container">
              <div class="video-mask contact-video-mask">
                <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster105.png" id="video105" class="contact-video-footer">
                  <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-105.mp4" type="video/mp4">
                  Your browser does not support HTML5 video.
                </video>
                <img id="105" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="product-list-group">
          <ul class="product-list">
            <li>
              Hot Slang Terms
            </li>
            <li>
              General Messaging
            </li>
            <li>
              Catchphrases
            </li>
          </ul>
        </div>

        <div class="product-question">
          <p class="product-questions">ARE THEY PHOTOS?</p>
        </div>
        <div class="product-video-group__item">

          <div class="product-video-container">
            <div class="video-mask contact-video-mask">
              <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster83.png" id="video83" class="contact-video-footer">
                <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-83.mp4" type="video/mp4">
                Your browser does not support HTML5 video.
              </video>
              <img id="83" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="product-list-group">
          <ul class="product-list">
            <li>
              Inspirational Quotes
            </li>
            <li>
              Advertisement
            </li>
            <li>
              Notifications
            </li>
          </ul>
        </div>

        <div class="product-question">
          <p class="product-questions">ANIMATED EMOJIS?</p>
        </div>
        <div class="product-video-group__item">

          <div class="product-video-container">
            <div class="video-mask contact-video-mask">
              <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster75.png" id="video40" class="contact-video-footer">
                <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-40.mp4" type="video/mp4">
                Your browser does not support HTML5 video.
              </video>
              <img id="40" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
            </div>
          </div>
        </div>
    </div>



  </div>
    <div style="margin-top:20px;">
      <div class="main-text">
        FACEPOP WILL SPARK A NEW HOT TREND WHILE IMPROVING CONCISENESS, CLARITY AND EFFICIENCY DURING ONE’S MESSAGING EXPERIENCE.
      </div>
    </div>
</section>

<script>
function playPause(clicked_id) {

    var clicked_video = 'video' + clicked_id;
    var myVideo = document.getElementById(clicked_video);
    var controllerImage = document.getElementById(clicked_id);

    if (myVideo.paused) {
        myVideo.play();
        $('#'+clicked_id).hide();
    }

    myVideo.onended = function() {
      $('#'+clicked_id).show();
      controllerImage.src = 'https://s3-us-west-2.amazonaws.com/facepop/play-button.png';
    };

}
</script>

app/views/pages/_survey.html.erb
<section id="survey-section" class="survey-section">
	<div class="page-title">
  		SURVEY
	</div>
	<div class="">
    <div class="product-video-container" style="margin-top:0; margin-bottom:20px;">
      <div class="video-mask contact-video-mask">
        <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster13.png" id="video13" class="contact-video-footer">
          <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-13.mp4" type="video/mp4">
          Your browser does not support HTML5 video.
        </video>
        <img id="13" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
      </div>
    </div>
		  <div class="main-text" style="margin:10px 0;">
  			FACEPOP IS IN THE EARLY STAGES OF BETA. YOUR INPUT IS IMPORTANT TO US AND TOGETHER WE 
  			CAN MAKE FACEPOP UNDENIABLE!
		  </div>

	</div>
  <hr>
  <div class="survey-slider">    
    <% @questions.order("created_at").each_with_index do |question, index| %>
    <div>
      <div id="question_<%= question.id %>" style="text-align: center">
        <span class="survey-questions"><%= question.question %></span>
        <div class="container survey-button">
          <% question.answers.order(:order).each_with_index do |answer, answer_index| %>
            <div style="position:relative;">

              <%= link_to "<div class='survey-btn'> #{answer.answer} </div>".html_safe, survey_answers_path(:vote_id => @current_vote, :question_id => question.id, :answer_id => answer.id), method: :post, class: "survey-link", remote: true %>

            </div>
            
          <% end %>
        </div>  
      </div>
    </div>
    <% end %>
    <div style="text-align: center;">
      <span style="font-size: 30px; color: #FFF">
      THANK YOU FOR COMPLETING OUR CONSUMER ANALYSIS SURVEY!</span>
    </div>
  </div>
  <div id="question-counter" class="question-counter">
    <div class="main-text">
      Question <span id="question-number">1</span> of <%= @questions.count %>
    </div>
  </div>
</section>

app/views/pages/_team.html.erb
<section class="team-section">
	<div class="page-title">
  		TEAM
	</div>

	<div class="product-video-container" style="margin-top:0;">
      <div class="video-mask contact-video-mask">
        <video poster="https://s3-us-west-2.amazonaws.com/facepop/poster29.png" id="video29" class="contact-video-footer">
          <source src="https://s3-us-west-2.amazonaws.com/facepop/video/video-29.mp4" type="video/mp4">
          Your browser does not support HTML5 video.
        </video>
        <img id="29" class="play-button product-video-play-image" onClick="playPause(this.id)" src="https://s3-us-west-2.amazonaws.com/facepop/play-button.png">
      </div>
    </div>
	<div class="row team">
  		<div class="col-md-3 team-bio">
  			<div class="team-bio_images">
  				<img src="https://s3-us-west-2.amazonaws.com/facepop/fp_logo_final.png" width="200" class="team-bio_image">
  			</div>

  			<b>Bervick J. Deculus II</b><div class="team-bio__title">

			CEO</div>
			<div class="team-bio__content">
			Founder of The Facepop Company (dba) and wildly motivated in offering a new communication tool that
			elevates today’s messaging experience around the globe. Bervick is an independent businessman for
			over 15 years with upwards of 20,000 hours in project management for independent entertainment
			companies and small businesses. Throughout his trails, Bervick continues to build and tailor quality
			assurance plans, refine creative development processes, conceptualize and develop viable
			products, services and events, and an all around natural creator and team player. While staying ahead
			of pop culture trends, Bervick truly manages to <em>"tastemake"</em> with an unmatched level of meticulosity.
			Bervick is a graduate of Howard University with a BA in Communications.</div>
			<div class="team-border"></div>
  		</div>

	  	<div class="col-md-3 team-bio bio-rel">
	  		<div class="team-bio_images">
  				<img src="https://s3-us-west-2.amazonaws.com/facepop/fp_logo_final.png" width="200" class="team-bio_image">
  			</div>

  			<b>Kareem Grimes</b><div class="team-bio__title">

			Co-Founder</div>
			<div class="team-bio__content">
			Kareem upholds the creative direction and partnership development for the
			The Facepop Company. Kareem, a 20 year seasoned actor, services major companies
			like, Samsung, AT&T and Mountain Dew as an event consultant and brand
			ambassador. Whether for sales, brand recognition, creative vetting and/or
			personal empowerment, Kareem's innate ability to create an impactful
			experience is proven to be unmatched. Due to his keen awareness of pop
			culture and its forthcoming trends, Kareem's ability to garner key relationships,
			locate product and talent with great potential is quite superior. Certainly,
			delivering creative needs for product development, marketing and building
			strategic partnerships to accelerate Facepop's growth can only come with
			ease. Kareem Grimes is a graduate of Cal State Los Angeles with a BA in
			Broadcast Journalism and Radio TV & Film.</div>
			<div class="team-border"></div>
	  	</div>

	  	<div class="col-md-3 team-bio bio-rel">
	  		<div class="team-bio_images">
  				<img src="https://s3-us-west-2.amazonaws.com/facepop/maginfo.png" class="team-bio_image"style="width:245px; bottom:85px;">
  			</div><br>
			<div class="team-bio__title">UX/UI Engineers</div>
			<div class="team-bio__content">
			From custom integrations and mobile applications, to enterprise search and big data analytics, we bring a world-class experience to clients of all sizes, across dissimilar industries and all with unique needs.  With years of experience providing innovative custom data and development solutions, we only offer the highest quality custom solutions with the most modern product architectures, practices and technologies.</div>
			<div class="team-border"></div>
	  	</div>

  		<div class="col-md-3 team-bio">
				<div class="team-bio_images">
  				<img src="https://s3-us-west-2.amazonaws.com/facepop/hs-new-logo.png" width="200" class="team-bio_image" style="bottom: 20px;">
  			</div>

  			<b>Harrison Schaen</b><div class="team-bio__title">

			CTO Advisor & Business Strategist</div>
			<div class="team-bio__content">
			Harrison is a graduate of Princeton University with a concentration in Computer Science and English.
			Harrison has more than 5 years of web and application development experience. Currently,
			Harrison is at the helm of Issue Fixers, Inc. (web/app development services), Sr. Web Developer at Bask
			Digital Media and founder of OK Feed Me (mobile application; beta). Along with his virtuosities within the booming tech space, Harrison continues to exercise his multimedia marketing abilities, and business strategies for both small and large businesses that drive company growth and success.</div>
			</div>
	</div>


</section>

app/views/pages/create.js.erb
create.js.erb

app/views/pages/home.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div>
<%= render "pages/hero" %>
<%= render "pages/slogan" %>
<% if false %>
  <%= render "pages/team" %>
  <%= render "pages/contact" %>
<% end %>
<%= render "pages/email" %>
</div>
<!-- Modal -->


<script type="text/javascript">
$(document).ready(function(){
  $('.survey-slider').slick({
    slidesToShow: 1,
    slidesToScroll: 1,
    arrows: false,
    infinite: false,
    draggable: false,
    swipe: false,
    touchMove: false
  });
});
</script>